Update commit-args.yaml

diff --git a/.github/workflows/commit-args.yaml b/.github/workflows/commit-args.yaml
--- a/.github/workflows/commit-args.yaml
+++ b/.github/workflows/commit-args.yaml
@@ -35,8 +35,8 @@ jobs:
             echo ::set-output name=test-output::$build
           fi          
                
-      - name: Supposedly failed
-        run: exit 1
+#       - name: Supposedly failed
+#         run: exit 1
   
         
       - name: echo outputs
