Update commit-args.yaml

diff --git a/.github/workflows/commit-args.yaml b/.github/workflows/commit-args.yaml
--- a/.github/workflows/commit-args.yaml
+++ b/.github/workflows/commit-args.yaml
@@ -39,28 +39,31 @@ jobs:
                
 #       - name: Supposedly failed
 #         run: exit 1
+      - name: test conditional
+        if: ${{ steps.test-if.outputs.test-output != 'null }}
+        run: echo ${{ steps.test-if.outputs.test-output }}
   
         
-      - name: echo outputs
-        run: echo ${{ steps.test-if.outputs.test-output }}
+#       - name: echo outputs
+#         run: echo ${{ steps.test-if.outputs.test-output }}
           
-  build-2:
-    runs-on: ubuntu-latest
-    if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'build')
-    steps:
-      - name: Succeed
-        run: |
-          echo "ok"
-          exit 1
+#   build-2:
+#     runs-on: ubuntu-latest
+#     if: github.event.issue.pull_request && startsWith(github.event.comment.body, 'build')
+#     steps:
+#       - name: Succeed
+#         run: |
+#           echo "ok"
+#           exit 1
     
-  run-if-fails:
-    runs-on: ubuntu-latest
-    needs: [build-1, build-2]
-    if: failure()
-    steps:
-      - name: Needs context
-        env:
-          NEEDS_CONTEXT: ${{ toJSON(needs) }}
-        run: |
-          echo "$NEEDS_CONTEXT"
-          echo ${{ needs.build-1.outputs.test-output }}
+#   run-if-fails:
+#     runs-on: ubuntu-latest
+#     needs: [build-1, build-2]
+#     if: failure()
+#     steps:
+#       - name: Needs context
+#         env:
+#           NEEDS_CONTEXT: ${{ toJSON(needs) }}
+#         run: |
+#           echo "$NEEDS_CONTEXT"
+#           echo ${{ needs.build-1.outputs.test-output }}
